(PARTIALLY) f2fs: support 3.0
Initial backporting done by nowcomputing,
(https://github.com/nowcomputing/f2fs-backports.git)

Additional patches required by upstream jaegeuk/f2fs.git/linux-3.4 done by arter97.

Andreas Blaesius:
Only apply chages to fix the following compiling issues if CONFIG_F2FS_FS_POSIX_ACL is enabled:
/home/android-andi/android/lp5.1/kernel/samsung/golden/fs/f2fs/acl.c:294:2: error: implicit declaration of function 'posix_acl_create' [-Werror=implicit-function-declaration]
  error = posix_acl_create(&acl, GFP_KERNEL, &inode->i_mode);
  ^
/home/android-andi/android/lp5.1/kernel/samsung/golden/fs/f2fs/acl.c: In function 'f2fs_acl_chmod':
/home/android-andi/android/lp5.1/kernel/samsung/golden/fs/f2fs/acl.c:320:2: error: implicit declaration of function 'posix_acl_chmod' [-Werror=implicit-function-declaration]
  error = posix_acl_chmod(&acl, GFP_KERNEL, mode);

Change-Id: I26b7a3180d7f751140dfc1f8ffd243816d6598af
Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>